name: tekartik_serial_wss_ui
description: A web app that uses AngularDart Components
version: 0.6.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular_router: any
  angular: '>=4.0.0-beta'
  angular_components: '>=0.6.0-beta'
  js: any
  tekartik_serial_wss:
    path: ../serial_wss
  tekartik_serial_wss_client:
    git: git://github.com/tekartik/serial_wss_client.dart
    version: '>=0.6.0'
  tekartik_angular_utils:
    git:
      url: git://github.com/tekartik/angular_utils.dart
      ref: dart1
    version: '>=0.2.0'
  tekartik_material_asset:
    git:
      url: git://github.com/tekartik/material_asset.dart
      ref: dart1
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0
  tekartik_pub:
    git:
      url: git://github.com/tekartik/pub.dart
      ref: dart1
    version: ">=0.6.2"
  grinder: any

transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
